sudo: required

language: python

python:
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev' # 3.5 development branch
  - 'nightly' # currently points to 3.6-dev

install:
  - travis_retry sudo apt-get install --no-install-recommends -y expect
  - pip install keyrings.alt

script: python setup.py test
