language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'

install:
  - pip install keyrings.alt coveralls
  - pip install -e .[testing]  # install setup + test requirements

script: python -m pytest

after_success: coveralls
